# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('battle_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=22)),
                ('attacker_size', models.IntegerField(null=True)),
                ('defender_size', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'BATTLE',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=22)),
                ('c_image', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'CHARACTER',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('h_name', models.CharField(max_length=22)),
                ('h_image', models.CharField(max_length=1024)),
                ('house_slogan', models.CharField(max_length=100)),
                ('house_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characterID', to='GameofThronesApp.Character')),
                ('leader_successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characterID2', to='GameofThronesApp.Character')),
            ],
            options={
                'db_table': 'HOUSE',
            },
        ),
        migrations.AddField(
            model_name='battle',
            name='attacker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houseID', to='GameofThronesApp.House'),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houseID2', to='GameofThronesApp.House'),
        ),
    ]
