# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameofThronesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='c_image',
            field=models.ImageField(max_length=1024, upload_to=''),
        ),
        migrations.AlterField(
            model_name='house',
            name='h_image',
            field=models.ImageField(max_length=1024, upload_to=''),
        ),
    ]
